export const plans = [
  {
    name: "For Players",
    description: "Build your profile, track your progress, and unlock new opportunities.",
    price: "€299",
    period: "/month",
    features: [
      "Personal performance dashboard",
      "Career and match statistics",
      "Training and progress tracking",
      "Contract and representation overview",
      "Visibility to verified agents and clubs",
      "Performance analytics and insights",
      "Profile exposure on the FootyLabs network",
    ],
  },
  {
    name: "For Agents",
    description: "Manage your players efficiently and grow your agency with data-driven tools.",
    price: "€1,899",
    period: "/month",
    features: [
      "Client and contract management",
      "Automated renewal and expiry reminders",
      "Performance and value analytics",
      "Scouting and recruitment support",
      "Direct communication with clubs and players",
      "Agency insights and reporting",
      "Access to verified player database",
    ],
  },
  {
    name: "For Clubs",
    description: "A complete management platform for squads, scouting, and recruitment.",
    price: "€3,499",
    period: "/month",
    features: [
      "Squad and player management system",
      "Recruitment and scouting workflows",
      "Performance and match analytics",
      "Player development monitoring",
      "Contract and transfer management",
      "Access to verified agents and players",
      "Collaboration and internal communication tools",
      "Dedicated account support",
    ],
    recommended: true,
  },
]
